name: Cron Job Example

on:
  schedule:
    # Runs every day at 12:00 AM UTC
    - cron: '* * * * *'

jobs:
  post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Make POST Request
        run: |
          curl -X POST \
            'https://stg.api.payroll.ioet.com/invoice/save' \
            --header 'Accept: */*' \
            --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' \
            --header 'Cron-Key: AIzaSyDh9JtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
